spring.application.name=user-service
spring.datasource.url=jdbc:sqlite:user.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# --- JPA / Hibernate settings ---
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8084
