server.port=8084
spring.application.name=user-service

# Eureka points to the registry container
eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/

# SQLite file inside container (mounted volume at /data)
spring.datasource.url=jdbc:sqlite:/data/user.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true