spring.application.name=catalogue-service
spring.datasource.url=jdbc:sqlite:catalogue.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# --- JPA / Hibernate settings ---
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=8081

eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
